### ISSUE TITLE
How to handle image that is less than 80 slices?

### ISSUE THREAD

**Issue by wshi8** [deepwise-code/DLIA#6]
I am testing on a MRI image sets, and some of the images have less than 80 slices, and the code throws the following errors during training, any advice how to handle images with < 80 slices?

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 49, in sampe_subjects
    img, gt, _delayed_transform_add_coords = AneurysmSampler(subject,  aneurysm_bbox[subject], spacing_zxy, image, aneurysm).sample(patch_num)
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 296, in sample
    negative_coords_list.extend(self.sample_negative_random(neg_num - neg_num // 2))
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 222, in sample_negative_random
    raise e
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 215, in sample_negative_random
    x = random.randint(0, self.img_size[0] - self.patch_size[0])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-15, -15)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 75, in
    main()
  File "main.py", line 71, in main
    main_worker(args)
  File "/home/ubuntu/DLIA/tasks/main.py", line 85, in main_worker
    trainer.train()
  File "/home/ubuntu/DLIA/tasks/main.py", line 40, in train
    self.task.train(epoch)
  File "/home/ubuntu/DLIA/utils/tools/util.py", line 47, in int_time
    res = func(*args, **kwargs)
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_seg.py", line 61, in train
    train_set = self.data_sampler.get_data_loader()
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 121, in get_data_loader
    img, gt, _delayed_transform_add_coords = obj.result()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 49, in sampe_subjects
    img, gt, _delayed_transform_add_coords = AneurysmSampler(subject,  aneurysm_bbox[subject], spacing_zxy, image, aneurysm).sample(patch_num)
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 296, in sample
    negative_coords_list.extend(self.sample_negative_random(neg_num - neg_num // 2))
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 222, in sample_negative_random
    raise e
  File "/home/ubuntu/DLIA/tasks/aneurysm/aneurysm_loader.py", line 215, in sample_negative_random
    x = random.randint(0, self.img_size[0] - self.patch_size[0])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-15, -15)

**Comment by deepwise-code** [comment]
in out dataset, the full head cta image almost have at least 180 slice with slicespacing ~0.625mm, and image width and height is 512; image with slice less than 80, suggestion is try to padding volume with zeros or mirror nearest;
